In [6]:
import torch
print(torch.__version__)

2.11.0+cpu


In [ ]:
#创建张量
#张量(Tensor)就是多维数组，是深度学习PyTorch,神经网络里最基础的数据容器
#1，从列表创建
a=torch.tensor([1,2,3])
print("a",a)
#2,从嵌套列表创建(二维)
b=torch.tensor([[1,2],[3,4]])
print("b:\n",b)
#3,全零矩阵
c=torch.zeros(3,3)
print("c:\n",c)
#4,全一矩阵
d=torch.ones(2,2)
print("d:\n",d)
#5,随机矩阵
e=torch.rand(3,3)#0,1的随机数
print("e:\n",e)
#6,等差数列
f=torch.arange(0,10,2)#start=0,end=10,step=2
print("f:",f)
#7,单位矩阵
g=torch.eye(3)
print("g:\n",g)

a tensor([1, 2, 3])
b:
 tensor([[1, 2],
        [3, 4]])
c:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
d:
 tensor([[1., 1.],
        [1., 1.]])
e:
 tensor([[0.8691, 0.0616, 0.4238],
        [0.0269, 0.4478, 0.1508],
        [0.7073, 0.4615, 0.9692]])
f: tensor([0, 2, 4, 6, 8])
g:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [9]:
x=torch.rand(2,3,4)
print("张量 x",x)
#查看形状
print("形状",x.shape)
#查看维度数
print("维度数",x.ndim)
#查看元素个数
print("元素个数",x.numel)
#查看数据类型
print("数据类型",x.dtype)
#查看设备
print("设备",x.device)

张量 x tensor([[[0.4044, 0.4078, 0.9781, 0.0040],
         [0.7780, 0.6012, 0.3396, 0.3207],
         [0.2292, 0.0272, 0.0178, 0.0539]],

        [[0.4149, 0.5820, 0.8577, 0.9077],
         [0.8262, 0.0681, 0.4920, 0.9138],
         [0.1946, 0.5577, 0.6616, 0.8650]]])
形状 torch.Size([2, 3, 4])
维度数 3
元素个数 <built-in method numel of Tensor object at 0x000001B7B0056C10>
数据类型 torch.float32
设备 cpu


In [11]:
#张量运算
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
#加法
print("加法",x+y)
print("加法函数",torch.add(x,y))

print("减法",x-y)
print("逐元素乘法",x*y)
print("除法",x/y)
#矩阵乘法
v1=torch.tensor([1,2,3])
v2=torch.tensor([4,5,6])
print("点积",torch.dot(v1,v2))
#二维矩阵乘法
m1=torch.tensor([[1,2],[3,4]])
m2=torch.tensor([[5,6],[7,8]])
print("矩阵乘法:\n",torch.matmul(m1,m2))
print("另一种写法:\n",m1@m2)

加法 tensor([5, 7, 9])
加法函数 tensor([5, 7, 9])
减法 tensor([-3, -3, -3])
逐元素乘法 tensor([ 4, 10, 18])
除法 tensor([0.2500, 0.4000, 0.5000])
点积 tensor(32)
矩阵乘法:
 tensor([[19, 22],
        [43, 50]])
另一种写法:
 tensor([[19, 22],
        [43, 50]])


In [ ]:
#张量索引和切片
# 创建一个5x5的随机矩阵
x = torch.rand(5, 5)
print("原矩阵:\n",x)
# 获取第一行
print("第一行:",x[0,:])#x[a:b,c:d]第a到b行的c到d列
# 获取第一列
print("第一列:", x[:,0])
# 获取第2-4行，第2-4列（注意：Python索引从0开始，1:4 表示索引1,2,3）
print("子区域:\n", x[1:4,1:4])
# 获取最后一行
print("最后一行:", x[-1,:])
# 获取对角线的元素
print("对角线:", torch.diag(x))
# 条件索引：找出大于0.5的元素
print("大于0.5的元素:", x[x>0.5])

原矩阵:
 tensor([[0.1534, 0.3557, 0.3479, 0.7901, 0.8658],
        [0.8128, 0.8910, 0.5221, 0.7133, 0.6311],
        [0.4869, 0.6988, 0.2084, 0.3322, 0.5654],
        [0.9823, 0.2309, 0.9368, 0.1043, 0.0128],
        [0.4801, 0.6597, 0.4974, 0.4155, 0.5799]])
第一行: tensor([0.1534, 0.3557, 0.3479, 0.7901, 0.8658])
第一列: tensor([0.1534, 0.8128, 0.4869, 0.9823, 0.4801])
子区域:
 tensor([[0.8910, 0.5221, 0.7133],
        [0.6988, 0.2084, 0.3322],
        [0.2309, 0.9368, 0.1043]])
最后一行: tensor([0.4801, 0.6597, 0.4974, 0.4155, 0.5799])
对角线: tensor([0.1534, 0.8910, 0.2084, 0.1043, 0.5799])
大于0.5的元素: tensor([0.7901, 0.8658, 0.8128, 0.8910, 0.5221, 0.7133, 0.6311, 0.6988, 0.5654,
        0.9823, 0.9368, 0.6597, 0.5799])


In [ ]:
#改变张量形状

# 创建0-11的序列
x=torch.arange(12)
print("原始:",x)

# 重塑为3行4列
print("reshape(3,4):\n", x.reshape(3, 4))

# view函数（类似reshape，但要求内存连续）
print("view(2,6):\n", x.view(2, 6))

# 展平（变成一维）
print("展平:", x.flatten())

# 增加维度(没有搞懂这一部分)
y = torch.tensor([1, 2, 3])
print("原始shape:", y.shape)
print("增加一维:", y.unsqueeze(0).shape)  # 在第0维增加一维
print(y)
print("增加另一维:", y.unsqueeze(1).shape)  # 在第1维增加一维
print(y)
# 减少维度（只能去掉大小为1的维度）
z = torch.rand(1, 3, 1, 4)
print("原始shape:", z.shape)
print("squeeze后:", z.squeeze().shape)  # 去掉所有大小为1的维度

原始: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
reshape(3,4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
view(2,6):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
展平: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
原始shape: torch.Size([3])
增加一维: torch.Size([1, 3])
tensor([1, 2, 3])
增加另一维: torch.Size([3, 1])
tensor([1, 2, 3])
原始shape: torch.Size([1, 3, 1, 4])
squeeze后: torch.Size([3, 4])


In [20]:
#广播机制（*****）
# 广播：不同形状的张量自动扩展为相同形状进行运算

# 例1：向量 + 标量
a=torch.tensor([1, 2, 3])
b=2
print("向量 + 标量:",a+b)# [1+2, 2+2, 3+2]

# 例2：不同维度的矩阵
c = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]])  # 形状 2x3
d = torch.tensor([10, 20, 30])  # 形状 3
print("矩阵 + 向量:\n", c + d)  
# d自动扩展为 [[10,20,30], [10,20,30]] 然后相加

# 例3：列向量 + 行向量
e = torch.tensor([[1], 
                  [2], 
                  [3]])  # 形状 3x1
f = torch.tensor([10, 20, 30])  # 形状 3
print("列向量 + 行向量:\n", e + f)
# e扩展为 [[1,1,1], [2,2,2], [3,3,3]]
# f扩展为 [[10,20,30], [10,20,30], [10,20,30]]
# 然后相加

向量 + 标量: tensor([3, 4, 5])
矩阵 + 向量:
 tensor([[11, 22, 33],
        [14, 25, 36]])
列向量 + 行向量:
 tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])


In [21]:
#数据类型的转换
# 创建不同数据类型的张量
a = torch.tensor([1, 2, 3], dtype=torch.float32)
print("float32:", a, a.dtype)

b = torch.tensor([1, 2, 3], dtype=torch.int64)
print("int64:", b, b.dtype)

# 类型转换
c = a.to(torch.int32)
print("转int32:", c, c.dtype)

d = b.to(torch.float32)
print("转float32:", d, d.dtype)

# 常用转换快捷方式
e = a.int()  # 转int
f = b.float()  # 转float

float32: tensor([1., 2., 3.]) torch.float32
int64: tensor([1, 2, 3]) torch.int64
转int32: tensor([1, 2, 3], dtype=torch.int32) torch.int32
转float32: tensor([1., 2., 3.]) torch.float32


In [22]:
# 检查是否有GPU
#GPU显卡的芯片，电脑的主处理器
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("使用GPU:", torch.cuda.get_device_name(0))
    
    # 把张量移到GPU
    x = torch.tensor([1, 2, 3])
    x_gpu = x.to(device)
    print("GPU上的张量:", x_gpu)
    
    # 在GPU上运算
    y_gpu = x_gpu * 2
    print("GPU运算结果:", y_gpu)
    
    # 移回CPU
    y_cpu = y_gpu.cpu()
    print("移回CPU:", y_cpu)
else:
    print("没有检测到GPU，使用CPU")
    # 没有GPU也能运行，只是慢一点

没有检测到GPU，使用CPU


In [ ]:
#练习
# 练习：用PyTorch实现线性回归的预测函数
# 给定权重 w 和偏置 b，输入特征 x，计算预测值 y = w*x + b

# 定义参数
w = torch.tensor([2.0, 3.0])  # 权重
b = torch.tensor(1.0)          # 偏置

# 输入数据（3个样本，每个样本2个特征）
X = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0],
                  [5.0, 6.0]])

# 计算预测值
# 方法1：手动计算
y_pred = torch.matmul(X, w) + b
print("预测值:", y_pred)

# 方法2：验证结果
print("期望值: [9, 19, 29]")

预测值: tensor([ 9., 19., 29.])
期望值: [9, 19, 29]
